//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("madoors_Model", "FK_ENTRANCE_BRANCH", "BRANCH", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Madoors.BRANCH), "ENTRANCE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Madoors.ENTRANCE), true)]
[assembly: EdmRelationshipAttribute("madoors_Model", "FK_LOGIN_ENTRANCE", "ENTRANCE", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Madoors.ENTRANCE), "LOGIN", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Madoors.LOGIN), true)]
[assembly: EdmRelationshipAttribute("madoors_Model", "FK_TOKEN_ENTRANCE", "ENTRANCE", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Madoors.ENTRANCE), "TOKEN", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Madoors.TOKEN), true)]
[assembly: EdmRelationshipAttribute("madoors_Model", "FK_CARPASS_ENTRANCE", "ENTRANCE", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Madoors.ENTRANCE), "CARPASS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Madoors.CARPASS), true)]

#endregion

namespace Madoors
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PersistencyManager : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PersistencyManager object using the connection string found in the 'PersistencyManager' section of the application configuration file.
        /// </summary>
        public PersistencyManager() : base("name=PersistencyManager", "PersistencyManager")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PersistencyManager object.
        /// </summary>
        public PersistencyManager(string connectionString) : base(connectionString, "PersistencyManager")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PersistencyManager object.
        /// </summary>
        public PersistencyManager(EntityConnection connection) : base(connection, "PersistencyManager")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BRANCH> BRANCH
        {
            get
            {
                if ((_BRANCH == null))
                {
                    _BRANCH = base.CreateObjectSet<BRANCH>("BRANCH");
                }
                return _BRANCH;
            }
        }
        private ObjectSet<BRANCH> _BRANCH;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DEVELOPER> DEVELOPER
        {
            get
            {
                if ((_DEVELOPER == null))
                {
                    _DEVELOPER = base.CreateObjectSet<DEVELOPER>("DEVELOPER");
                }
                return _DEVELOPER;
            }
        }
        private ObjectSet<DEVELOPER> _DEVELOPER;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LOGIN> LOGIN
        {
            get
            {
                if ((_LOGIN == null))
                {
                    _LOGIN = base.CreateObjectSet<LOGIN>("LOGIN");
                }
                return _LOGIN;
            }
        }
        private ObjectSet<LOGIN> _LOGIN;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TOKEN> TOKEN
        {
            get
            {
                if ((_TOKEN == null))
                {
                    _TOKEN = base.CreateObjectSet<TOKEN>("TOKEN");
                }
                return _TOKEN;
            }
        }
        private ObjectSet<TOKEN> _TOKEN;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CARPASS> CARPASS
        {
            get
            {
                if ((_CARPASS == null))
                {
                    _CARPASS = base.CreateObjectSet<CARPASS>("CARPASS");
                }
                return _CARPASS;
            }
        }
        private ObjectSet<CARPASS> _CARPASS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ENTRANCE> ENTRANCE
        {
            get
            {
                if ((_ENTRANCE == null))
                {
                    _ENTRANCE = base.CreateObjectSet<ENTRANCE>("ENTRANCE");
                }
                return _ENTRANCE;
            }
        }
        private ObjectSet<ENTRANCE> _ENTRANCE;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BRANCH EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBRANCH(BRANCH bRANCH)
        {
            base.AddObject("BRANCH", bRANCH);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DEVELOPER EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDEVELOPER(DEVELOPER dEVELOPER)
        {
            base.AddObject("DEVELOPER", dEVELOPER);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LOGIN EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLOGIN(LOGIN lOGIN)
        {
            base.AddObject("LOGIN", lOGIN);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TOKEN EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTOKEN(TOKEN tOKEN)
        {
            base.AddObject("TOKEN", tOKEN);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CARPASS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCARPASS(CARPASS cARPASS)
        {
            base.AddObject("CARPASS", cARPASS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ENTRANCE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToENTRANCE(ENTRANCE eNTRANCE)
        {
            base.AddObject("ENTRANCE", eNTRANCE);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="madoors_Model", Name="BRANCH")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BRANCH : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BRANCH object.
        /// </summary>
        /// <param name="branchID">Initial value of the branchID property.</param>
        public static BRANCH CreateBRANCH(global::System.Guid branchID)
        {
            BRANCH bRANCH = new BRANCH();
            bRANCH.branchID = branchID;
            return bRANCH;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid branchID
        {
            get
            {
                return _branchID;
            }
            set
            {
                if (_branchID != value)
                {
                    OnbranchIDChanging(value);
                    ReportPropertyChanging("branchID");
                    _branchID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("branchID");
                    OnbranchIDChanged();
                }
            }
        }
        private global::System.Guid _branchID;
        partial void OnbranchIDChanging(global::System.Guid value);
        partial void OnbranchIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String branchName
        {
            get
            {
                return _branchName;
            }
            set
            {
                OnbranchNameChanging(value);
                ReportPropertyChanging("branchName");
                _branchName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("branchName");
                OnbranchNameChanged();
            }
        }
        private global::System.String _branchName;
        partial void OnbranchNameChanging(global::System.String value);
        partial void OnbranchNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("madoors_Model", "FK_ENTRANCE_BRANCH", "ENTRANCE")]
        public EntityCollection<ENTRANCE> ENTRANCE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ENTRANCE>("madoors_Model.FK_ENTRANCE_BRANCH", "ENTRANCE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ENTRANCE>("madoors_Model.FK_ENTRANCE_BRANCH", "ENTRANCE", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="madoors_Model", Name="CARPASS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CARPASS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CARPASS object.
        /// </summary>
        /// <param name="carPassID">Initial value of the carPassID property.</param>
        public static CARPASS CreateCARPASS(global::System.Guid carPassID)
        {
            CARPASS cARPASS = new CARPASS();
            cARPASS.carPassID = carPassID;
            return cARPASS;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid carPassID
        {
            get
            {
                return _carPassID;
            }
            set
            {
                if (_carPassID != value)
                {
                    OncarPassIDChanging(value);
                    ReportPropertyChanging("carPassID");
                    _carPassID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("carPassID");
                    OncarPassIDChanged();
                }
            }
        }
        private global::System.Guid _carPassID;
        partial void OncarPassIDChanging(global::System.Guid value);
        partial void OncarPassIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> entranceID
        {
            get
            {
                return _entranceID;
            }
            set
            {
                OnentranceIDChanging(value);
                ReportPropertyChanging("entranceID");
                _entranceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("entranceID");
                OnentranceIDChanged();
            }
        }
        private Nullable<global::System.Guid> _entranceID;
        partial void OnentranceIDChanging(Nullable<global::System.Guid> value);
        partial void OnentranceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String plateNo
        {
            get
            {
                return _plateNo;
            }
            set
            {
                OnplateNoChanging(value);
                ReportPropertyChanging("plateNo");
                _plateNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("plateNo");
                OnplateNoChanged();
            }
        }
        private global::System.String _plateNo;
        partial void OnplateNoChanging(global::System.String value);
        partial void OnplateNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> state
        {
            get
            {
                return _state;
            }
            set
            {
                OnstateChanging(value);
                ReportPropertyChanging("state");
                _state = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("state");
                OnstateChanged();
            }
        }
        private Nullable<global::System.Int32> _state;
        partial void OnstateChanging(Nullable<global::System.Int32> value);
        partial void OnstateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String time
        {
            get
            {
                return _time;
            }
            set
            {
                OntimeChanging(value);
                ReportPropertyChanging("time");
                _time = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("time");
                OntimeChanged();
            }
        }
        private global::System.String _time;
        partial void OntimeChanging(global::System.String value);
        partial void OntimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] image
        {
            get
            {
                return StructuralObject.GetValidValue(_image);
            }
            set
            {
                OnimageChanging(value);
                ReportPropertyChanging("image");
                _image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("image");
                OnimageChanged();
            }
        }
        private global::System.Byte[] _image;
        partial void OnimageChanging(global::System.Byte[] value);
        partial void OnimageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dbCreationTime
        {
            get
            {
                return _dbCreationTime;
            }
            set
            {
                OndbCreationTimeChanging(value);
                ReportPropertyChanging("dbCreationTime");
                _dbCreationTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dbCreationTime");
                OndbCreationTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _dbCreationTime;
        partial void OndbCreationTimeChanging(Nullable<global::System.DateTime> value);
        partial void OndbCreationTimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("madoors_Model", "FK_CARPASS_ENTRANCE", "ENTRANCE")]
        public ENTRANCE ENTRANCE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ENTRANCE>("madoors_Model.FK_CARPASS_ENTRANCE", "ENTRANCE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ENTRANCE>("madoors_Model.FK_CARPASS_ENTRANCE", "ENTRANCE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ENTRANCE> ENTRANCEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ENTRANCE>("madoors_Model.FK_CARPASS_ENTRANCE", "ENTRANCE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ENTRANCE>("madoors_Model.FK_CARPASS_ENTRANCE", "ENTRANCE", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="madoors_Model", Name="DEVELOPER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DEVELOPER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DEVELOPER object.
        /// </summary>
        /// <param name="developerID">Initial value of the developerID property.</param>
        public static DEVELOPER CreateDEVELOPER(global::System.Guid developerID)
        {
            DEVELOPER dEVELOPER = new DEVELOPER();
            dEVELOPER.developerID = developerID;
            return dEVELOPER;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid developerID
        {
            get
            {
                return _developerID;
            }
            set
            {
                if (_developerID != value)
                {
                    OndeveloperIDChanging(value);
                    ReportPropertyChanging("developerID");
                    _developerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("developerID");
                    OndeveloperIDChanged();
                }
            }
        }
        private global::System.Guid _developerID;
        partial void OndeveloperIDChanging(global::System.Guid value);
        partial void OndeveloperIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String developerName
        {
            get
            {
                return _developerName;
            }
            set
            {
                OndeveloperNameChanging(value);
                ReportPropertyChanging("developerName");
                _developerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("developerName");
                OndeveloperNameChanged();
            }
        }
        private global::System.String _developerName;
        partial void OndeveloperNameChanging(global::System.String value);
        partial void OndeveloperNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="madoors_Model", Name="ENTRANCE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ENTRANCE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ENTRANCE object.
        /// </summary>
        /// <param name="entranceID">Initial value of the entranceID property.</param>
        public static ENTRANCE CreateENTRANCE(global::System.Guid entranceID)
        {
            ENTRANCE eNTRANCE = new ENTRANCE();
            eNTRANCE.entranceID = entranceID;
            return eNTRANCE;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid entranceID
        {
            get
            {
                return _entranceID;
            }
            set
            {
                if (_entranceID != value)
                {
                    OnentranceIDChanging(value);
                    ReportPropertyChanging("entranceID");
                    _entranceID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("entranceID");
                    OnentranceIDChanged();
                }
            }
        }
        private global::System.Guid _entranceID;
        partial void OnentranceIDChanging(global::System.Guid value);
        partial void OnentranceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> branchID
        {
            get
            {
                return _branchID;
            }
            set
            {
                OnbranchIDChanging(value);
                ReportPropertyChanging("branchID");
                _branchID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("branchID");
                OnbranchIDChanged();
            }
        }
        private Nullable<global::System.Guid> _branchID;
        partial void OnbranchIDChanging(Nullable<global::System.Guid> value);
        partial void OnbranchIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String entranceName
        {
            get
            {
                return _entranceName;
            }
            set
            {
                OnentranceNameChanging(value);
                ReportPropertyChanging("entranceName");
                _entranceName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("entranceName");
                OnentranceNameChanged();
            }
        }
        private global::System.String _entranceName;
        partial void OnentranceNameChanging(global::System.String value);
        partial void OnentranceNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("madoors_Model", "FK_ENTRANCE_BRANCH", "BRANCH")]
        public BRANCH BRANCH
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BRANCH>("madoors_Model.FK_ENTRANCE_BRANCH", "BRANCH").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BRANCH>("madoors_Model.FK_ENTRANCE_BRANCH", "BRANCH").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BRANCH> BRANCHReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BRANCH>("madoors_Model.FK_ENTRANCE_BRANCH", "BRANCH");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BRANCH>("madoors_Model.FK_ENTRANCE_BRANCH", "BRANCH", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("madoors_Model", "FK_LOGIN_ENTRANCE", "LOGIN")]
        public EntityCollection<LOGIN> LOGIN
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<LOGIN>("madoors_Model.FK_LOGIN_ENTRANCE", "LOGIN");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<LOGIN>("madoors_Model.FK_LOGIN_ENTRANCE", "LOGIN", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("madoors_Model", "FK_TOKEN_ENTRANCE", "TOKEN")]
        public EntityCollection<TOKEN> TOKEN
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TOKEN>("madoors_Model.FK_TOKEN_ENTRANCE", "TOKEN");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TOKEN>("madoors_Model.FK_TOKEN_ENTRANCE", "TOKEN", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("madoors_Model", "FK_CARPASS_ENTRANCE", "CARPASS")]
        public EntityCollection<CARPASS> CARPASS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CARPASS>("madoors_Model.FK_CARPASS_ENTRANCE", "CARPASS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CARPASS>("madoors_Model.FK_CARPASS_ENTRANCE", "CARPASS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="madoors_Model", Name="LOGIN")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LOGIN : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LOGIN object.
        /// </summary>
        /// <param name="loginID">Initial value of the loginID property.</param>
        public static LOGIN CreateLOGIN(global::System.Guid loginID)
        {
            LOGIN lOGIN = new LOGIN();
            lOGIN.loginID = loginID;
            return lOGIN;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid loginID
        {
            get
            {
                return _loginID;
            }
            set
            {
                if (_loginID != value)
                {
                    OnloginIDChanging(value);
                    ReportPropertyChanging("loginID");
                    _loginID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("loginID");
                    OnloginIDChanged();
                }
            }
        }
        private global::System.Guid _loginID;
        partial void OnloginIDChanging(global::System.Guid value);
        partial void OnloginIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> entranceID
        {
            get
            {
                return _entranceID;
            }
            set
            {
                OnentranceIDChanging(value);
                ReportPropertyChanging("entranceID");
                _entranceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("entranceID");
                OnentranceIDChanged();
            }
        }
        private Nullable<global::System.Guid> _entranceID;
        partial void OnentranceIDChanging(Nullable<global::System.Guid> value);
        partial void OnentranceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String deviceKey
        {
            get
            {
                return _deviceKey;
            }
            set
            {
                OndeviceKeyChanging(value);
                ReportPropertyChanging("deviceKey");
                _deviceKey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("deviceKey");
                OndeviceKeyChanged();
            }
        }
        private global::System.String _deviceKey;
        partial void OndeviceKeyChanging(global::System.String value);
        partial void OndeviceKeyChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("madoors_Model", "FK_LOGIN_ENTRANCE", "ENTRANCE")]
        public ENTRANCE ENTRANCE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ENTRANCE>("madoors_Model.FK_LOGIN_ENTRANCE", "ENTRANCE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ENTRANCE>("madoors_Model.FK_LOGIN_ENTRANCE", "ENTRANCE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ENTRANCE> ENTRANCEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ENTRANCE>("madoors_Model.FK_LOGIN_ENTRANCE", "ENTRANCE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ENTRANCE>("madoors_Model.FK_LOGIN_ENTRANCE", "ENTRANCE", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="madoors_Model", Name="TOKEN")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TOKEN : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TOKEN object.
        /// </summary>
        /// <param name="tokenID">Initial value of the tokenID property.</param>
        public static TOKEN CreateTOKEN(global::System.Guid tokenID)
        {
            TOKEN tOKEN = new TOKEN();
            tOKEN.tokenID = tokenID;
            return tOKEN;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid tokenID
        {
            get
            {
                return _tokenID;
            }
            set
            {
                if (_tokenID != value)
                {
                    OntokenIDChanging(value);
                    ReportPropertyChanging("tokenID");
                    _tokenID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("tokenID");
                    OntokenIDChanged();
                }
            }
        }
        private global::System.Guid _tokenID;
        partial void OntokenIDChanging(global::System.Guid value);
        partial void OntokenIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> entranceID
        {
            get
            {
                return _entranceID;
            }
            set
            {
                OnentranceIDChanging(value);
                ReportPropertyChanging("entranceID");
                _entranceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("entranceID");
                OnentranceIDChanged();
            }
        }
        private Nullable<global::System.Guid> _entranceID;
        partial void OnentranceIDChanging(Nullable<global::System.Guid> value);
        partial void OnentranceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> tokenGenerationTime
        {
            get
            {
                return _tokenGenerationTime;
            }
            set
            {
                OntokenGenerationTimeChanging(value);
                ReportPropertyChanging("tokenGenerationTime");
                _tokenGenerationTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tokenGenerationTime");
                OntokenGenerationTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _tokenGenerationTime;
        partial void OntokenGenerationTimeChanging(Nullable<global::System.DateTime> value);
        partial void OntokenGenerationTimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("madoors_Model", "FK_TOKEN_ENTRANCE", "ENTRANCE")]
        public ENTRANCE ENTRANCE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ENTRANCE>("madoors_Model.FK_TOKEN_ENTRANCE", "ENTRANCE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ENTRANCE>("madoors_Model.FK_TOKEN_ENTRANCE", "ENTRANCE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ENTRANCE> ENTRANCEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ENTRANCE>("madoors_Model.FK_TOKEN_ENTRANCE", "ENTRANCE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ENTRANCE>("madoors_Model.FK_TOKEN_ENTRANCE", "ENTRANCE", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
